// MODEL_DICT removed — all predictions are handled by sklearn RandomForest on the backend.
// See: Backend/ml_model.py, POST /analys

import type { Lang } from "./i18n";

const DISEASE_LABELS_I18N: Record<string, Record<Lang, string>> = {
  // Legacy (kept for backward compatibility)
  "Gastroenteritis": { ru: "Гастроэнтерит (Кишечная инфекция)", en: "Gastroenteritis (Intestinal Infection)", kk: "Гастроэнтерит (Ішек инфекциясы)" },
  "Scarlet Fever": { ru: "Скарлатина", en: "Scarlet Fever", kk: "Қызылша" },
  "Eczema": { ru: "Экзема / Дерматит", en: "Eczema / Dermatitis", kk: "Экзема / Дерматит" },
  "Asthma": { ru: "Бронхиальная астма", en: "Bronchial Asthma", kk: "Бронхиалды астма" },
  "Type 1 Diabetes": { ru: "Сахарный диабет 1 типа (Подозрение)", en: "Type 1 Diabetes (Suspected)", kk: "1-ші типті қант диабеті (Күдік)" },
  "Meningitis": { ru: "Менингит", en: "Meningitis", kk: "Менингит" },
  "Chickenpox": { ru: "Ветрянка", en: "Chickenpox", kk: "Су шешек" },
  "Appendicitis": { ru: "Аппендицит", en: "Appendicitis", kk: "Аппендицит" },
  "Common Cold": { ru: "Простуда (ОРЗ)", en: "Common Cold (ARI)", kk: "Суық тию (ЖРА)" },
  // DDXPlus 49 diseases
  "Acute COPD exacerbation / infection": { ru: "Обострение ХОБЛ / инфекция", en: "Acute COPD Exacerbation / Infection", kk: "СОЗО асқынуы / инфекция" },
  "Acute dystonic reactions": { ru: "Острые дистонические реакции", en: "Acute Dystonic Reactions", kk: "Жіті дистониялық реакциялар" },
  "Acute laryngitis": { ru: "Острый ларингит", en: "Acute Laryngitis", kk: "Жіті ларингит" },
  "Acute otitis media": { ru: "Острый средний отит", en: "Acute Otitis Media", kk: "Жіті орта отит" },
  "Acute pulmonary edema": { ru: "Острый отёк лёгких", en: "Acute Pulmonary Edema", kk: "Жіті өкпе ісінуі" },
  "Acute rhinosinusitis": { ru: "Острый риносинусит", en: "Acute Rhinosinusitis", kk: "Жіті риносинусит" },
  "Allergic sinusitis": { ru: "Аллергический синусит", en: "Allergic Sinusitis", kk: "Аллергиялық синусит" },
  "Anaphylaxis": { ru: "Анафилаксия", en: "Anaphylaxis", kk: "Анафилаксия" },
  "Anemia": { ru: "Анемия", en: "Anemia", kk: "Анемия" },
  "Atrial fibrillation": { ru: "Мерцательная аритмия", en: "Atrial Fibrillation", kk: "Жүрек жыпылықтауы" },
  "Boerhaave": { ru: "Синдром Бурхаве (разрыв пищевода)", en: "Boerhaave Syndrome (Esophageal Rupture)", kk: "Бурхаве синдромы (өңеш жарылуы)" },
  "Bronchiectasis": { ru: "Бронхоэктатическая болезнь", en: "Bronchiectasis", kk: "Бронхоэктатикалық ауру" },
  "Bronchiolitis": { ru: "Бронхиолит", en: "Bronchiolitis", kk: "Бронхиолит" },
  "Bronchitis": { ru: "Бронхит", en: "Bronchitis", kk: "Бронхит" },
  "Bronchospasm / acute asthma exacerbation": { ru: "Бронхоспазм / Обострение астмы", en: "Bronchospasm / Acute Asthma Exacerbation", kk: "Бронхоспазм / Астма асқынуы" },
  "Chagas": { ru: "Болезнь Шагаса", en: "Chagas Disease", kk: "Шагас ауруы" },
  "Chronic rhinosinusitis": { ru: "Хронический риносинусит", en: "Chronic Rhinosinusitis", kk: "Созылмалы риносинусит" },
  "Cluster headache": { ru: "Кластерная головная боль", en: "Cluster Headache", kk: "Кластерлік бас ауруы" },
  "Croup": { ru: "Круп (Острый ларинготрахеит)", en: "Croup (Acute Laryngotracheitis)", kk: "Круп (Жіті ларинготрахеит)" },
  "Ebola": { ru: "Лихорадка Эбола", en: "Ebola Virus Disease", kk: "Эбола безгегі" },
  "Epiglottitis": { ru: "Эпиглоттит", en: "Epiglottitis", kk: "Эпиглоттит" },
  "GERD": { ru: "ГЭРБ (Гастроэзофагеальный рефлюкс)", en: "GERD (Gastroesophageal Reflux Disease)", kk: "ГЭРБ (Асқазан-өңеш рефлюксі)" },
  "Guillain-Barré syndrome": { ru: "Синдром Гийена-Барре", en: "Guillain-Barré Syndrome", kk: "Гийен-Барре синдромы" },
  "HIV (initial infection)": { ru: "ВИЧ (первичная инфекция)", en: "HIV (Initial Infection)", kk: "АИТВ (алғашқы инфекция)" },
  "Influenza": { ru: "Грипп / ОРВИ", en: "Influenza / ARVI", kk: "Тұмау / ЖРВИ" },
  "Inguinal hernia": { ru: "Паховая грыжа", en: "Inguinal Hernia", kk: "Шап жарығы" },
  "Larygospasm": { ru: "Ларингоспазм", en: "Laryngospasm", kk: "Ларингоспазм" },
  "Localized edema": { ru: "Локализованный отёк", en: "Localized Edema", kk: "Жергілікті ісіну" },
  "Myasthenia gravis": { ru: "Миастения гравис", en: "Myasthenia Gravis", kk: "Миастения гравис" },
  "Myocarditis": { ru: "Миокардит", en: "Myocarditis", kk: "Миокардит" },
  "PSVT": { ru: "Пароксизмальная суправентрикулярная тахикардия", en: "Paroxysmal Supraventricular Tachycardia", kk: "Пароксизмалды суправентрикулярлық тахикардия" },
  "Pancreatic neoplasm": { ru: "Новообразование поджелудочной железы", en: "Pancreatic Neoplasm", kk: "Ұйқы безінің ісігі" },
  "Panic attack": { ru: "Паническая атака", en: "Panic Attack", kk: "Паникалық шабуыл" },
  "Pericarditis": { ru: "Перикардит", en: "Pericarditis", kk: "Перикардит" },
  "Pneumonia": { ru: "Пневмония", en: "Pneumonia", kk: "Пневмония" },
  "Possible NSTEMI / STEMI": { ru: "Возможный инфаркт миокарда (НСТМИ/СТМИ)", en: "Possible NSTEMI / STEMI (Heart Attack)", kk: "Мүмкін жүрек инфаркті (НСТМИ/СТМИ)" },
  "Pulmonary embolism": { ru: "Тромбоэмболия лёгочной артерии (ТЭЛА)", en: "Pulmonary Embolism (PE)", kk: "Өкпе артериясының тромбоэмболиясы" },
  "Pulmonary neoplasm": { ru: "Новообразование лёгкого", en: "Pulmonary Neoplasm", kk: "Өкпе ісігі" },
  "SLE": { ru: "Системная красная волчанка", en: "Systemic Lupus Erythematosus (SLE)", kk: "Жүйелі қызыл жегі" },
  "Sarcoidosis": { ru: "Саркоидоз", en: "Sarcoidosis", kk: "Саркоидоз" },
  "Scombroid food poisoning": { ru: "Скомброидное пищевое отравление", en: "Scombroid Food Poisoning", kk: "Скомброидтық тамақ улануы" },
  "Spontaneous pneumothorax": { ru: "Спонтанный пневмоторакс", en: "Spontaneous Pneumothorax", kk: "Стихиялы пневмоторакс" },
  "Spontaneous rib fracture": { ru: "Спонтанный перелом ребра", en: "Spontaneous Rib Fracture", kk: "Стихиялы қабырға сынуы" },
  "Stable angina": { ru: "Стабильная стенокардия", en: "Stable Angina", kk: "Тұрақты стенокардия" },
  "Tuberculosis": { ru: "Туберкулёз", en: "Tuberculosis (TB)", kk: "Туберкулез" },
  "URTI": { ru: "ОРВИ (инфекция верхних дыхательных путей)", en: "URTI (Upper Respiratory Tract Infection)", kk: "ЖРВИ (жоғарғы тыныс жолдарының инфекциясы)" },
  "Unstable angina": { ru: "Нестабильная стенокардия", en: "Unstable Angina", kk: "Тұрақсыз стенокардия" },
  "Viral pharyngitis": { ru: "Вирусный фарингит", en: "Viral Pharyngitis", kk: "Вирустық фарингит" },
  "Whooping cough": { ru: "Коклюш", en: "Whooping Cough (Pertussis)", kk: "Қақырықты жөтел" },
};

const DISEASE_DOCTORS_I18N: Record<string, Record<Lang, string>> = {
  "Gastroenteritis": { ru: "Гастроэнтеролог / Инфекционист", en: "Gastroenterologist / Infectious Disease Specialist", kk: "Гастроэнтеролог / Инфекционист" },
  "Croup": { ru: "Педиатр / Скорая (если задыхается)", en: "Pediatrician / Emergency (if choking)", kk: "Педиатр / Жедел жәрдем (тұншығу кезінде)" },
  "Scarlet Fever": { ru: "Инфекционист / Педиатр", en: "Infectious Disease Specialist / Pediatrician", kk: "Инфекционист / Педиатр" },
  "Eczema": { ru: "Дерматолог", en: "Dermatologist", kk: "Дерматолог" },
  "Asthma": { ru: "Пульмонолог / Аллерголог", en: "Pulmonologist / Allergist", kk: "Пульмонолог / Аллерголог" },
  "Type 1 Diabetes": { ru: "Эндокринолог (Срочно)", en: "Endocrinologist (Urgent)", kk: "Эндокринолог (Шұғыл)" },
  "Bronchiolitis": { ru: "Педиатр / Пульмонолог", en: "Pediatrician / Pulmonologist", kk: "Педиатр / Пульмонолог" },
  "Meningitis": { ru: "СКОРАЯ ПОМОЩЬ (103) / Невролог", en: "EMERGENCY (911) / Neurologist", kk: "ЖЕДЕЛ ЖӘРДЕМ (103) / Невролог" },
  "Chickenpox": { ru: "Терапевт (вызов на дом)", en: "GP (home visit)", kk: "Терапевт (үйге шақыру)" },
  "Appendicitis": { ru: "СКОРАЯ ПОМОЩЬ (Хирургия)", en: "EMERGENCY (Surgery)", kk: "ЖЕДЕЛ ЖӘРДЕМ (Хирургия)" },
  "Common Cold": { ru: "Терапевт", en: "General Practitioner", kk: "Терапевт" },
  "Acute COPD exacerbation / infection": { ru: "Пульмонолог / Терапевт", en: "Pulmonologist / GP", kk: "Пульмонолог / Терапевт" },
  "Acute dystonic reactions": { ru: "Невролог / Скорая помощь", en: "Neurologist / Emergency", kk: "Невролог / Жедел жәрдем" },
  "Acute laryngitis": { ru: "ЛОР-врач", en: "ENT Specialist", kk: "ЛОР дәрігері" },
  "Acute otitis media": { ru: "ЛОР-врач / Педиатр", en: "ENT / Pediatrician", kk: "ЛОР / Педиатр" },
  "Acute pulmonary edema": { ru: "СКОРАЯ ПОМОЩЬ (103)", en: "EMERGENCY (911)", kk: "ЖЕДЕЛ ЖӘРДЕМ (103)" },
  "Acute rhinosinusitis": { ru: "ЛОР-врач", en: "ENT Specialist", kk: "ЛОР дәрігері" },
  "Allergic sinusitis": { ru: "Аллерголог / ЛОР-врач", en: "Allergist / ENT", kk: "Аллерголог / ЛОР" },
  "Anaphylaxis": { ru: "СКОРАЯ ПОМОЩЬ (103)", en: "EMERGENCY (911)", kk: "ЖЕДЕЛ ЖӘРДЕМ (103)" },
  "Anemia": { ru: "Гематолог / Терапевт", en: "Hematologist / GP", kk: "Гематолог / Терапевт" },
  "Atrial fibrillation": { ru: "Кардиолог", en: "Cardiologist", kk: "Кардиолог" },
  "Boerhaave": { ru: "СКОРАЯ ПОМОЩЬ (103) / Хирург", en: "EMERGENCY (911) / Surgeon", kk: "ЖЕДЕЛ ЖӘРДЕМ (103) / Хирург" },
  "Bronchiectasis": { ru: "Пульмонолог", en: "Pulmonologist", kk: "Пульмонолог" },
  "Bronchitis": { ru: "Терапевт / Педиатр", en: "GP / Pediatrician", kk: "Терапевт / Педиатр" },
  "Bronchospasm / acute asthma exacerbation": { ru: "Аллерголог / СКОРАЯ при тяжёлом приступе", en: "Allergist / Emergency for severe attack", kk: "Аллерголог / Ауыр шабуылда жедел жәрдем" },
  "Chagas": { ru: "Инфекционист", en: "Infectious Disease Specialist", kk: "Инфекционист" },
  "Chronic rhinosinusitis": { ru: "ЛОР-врач", en: "ENT Specialist", kk: "ЛОР дәрігері" },
  "Cluster headache": { ru: "Невролог", en: "Neurologist", kk: "Невролог" },
  "Ebola": { ru: "СКОРАЯ ПОМОЩЬ (103) / Инфекционист", en: "EMERGENCY (911) / Infectious Disease Specialist", kk: "ЖЕДЕЛ ЖӘРДЕМ (103) / Инфекционист" },
  "Epiglottitis": { ru: "СКОРАЯ ПОМОЩЬ (103) / ЛОР-врач", en: "EMERGENCY (911) / ENT", kk: "ЖЕДЕЛ ЖӘРДЕМ (103) / ЛОР" },
  "GERD": { ru: "Гастроэнтеролог", en: "Gastroenterologist", kk: "Гастроэнтеролог" },
  "Guillain-Barré syndrome": { ru: "Невролог / СКОРАЯ ПОМОЩЬ", en: "Neurologist / Emergency", kk: "Невролог / Жедел жәрдем" },
  "HIV (initial infection)": { ru: "Инфекционист", en: "Infectious Disease Specialist", kk: "Инфекционист" },
  "Influenza": { ru: "Терапевт / Педиатр", en: "GP / Pediatrician", kk: "Терапевт / Педиатр" },
  "Inguinal hernia": { ru: "Хирург", en: "Surgeon", kk: "Хирург" },
  "Larygospasm": { ru: "ЛОР-врач", en: "ENT Specialist", kk: "ЛОР дәрігері" },
  "Localized edema": { ru: "Терапевт / Хирург", en: "GP / Surgeon", kk: "Терапевт / Хирург" },
  "Myasthenia gravis": { ru: "Невролог", en: "Neurologist", kk: "Невролог" },
  "Myocarditis": { ru: "Кардиолог / СКОРАЯ ПОМОЩЬ", en: "Cardiologist / Emergency", kk: "Кардиолог / Жедел жәрдем" },
  "PSVT": { ru: "Кардиолог", en: "Cardiologist", kk: "Кардиолог" },
  "Pancreatic neoplasm": { ru: "Онколог / Гастроэнтеролог", en: "Oncologist / Gastroenterologist", kk: "Онколог / Гастроэнтеролог" },
  "Panic attack": { ru: "Психиатр / Психолог", en: "Psychiatrist / Psychologist", kk: "Психиатр / Психолог" },
  "Pericarditis": { ru: "Кардиолог", en: "Cardiologist", kk: "Кардиолог" },
  "Pneumonia": { ru: "Терапевт / Пульмонолог", en: "GP / Pulmonologist", kk: "Терапевт / Пульмонолог" },
  "Possible NSTEMI / STEMI": { ru: "СКОРАЯ ПОМОЩЬ (103)", en: "EMERGENCY (911)", kk: "ЖЕДЕЛ ЖӘРДЕМ (103)" },
  "Pulmonary embolism": { ru: "СКОРАЯ ПОМОЩЬ (103)", en: "EMERGENCY (911)", kk: "ЖЕДЕЛ ЖӘРДЕМ (103)" },
  "Pulmonary neoplasm": { ru: "Онколог / Пульмонолог", en: "Oncologist / Pulmonologist", kk: "Онколог / Пульмонолог" },
  "SLE": { ru: "Ревматолог", en: "Rheumatologist", kk: "Ревматолог" },
  "Sarcoidosis": { ru: "Пульмонолог / Ревматолог", en: "Pulmonologist / Rheumatologist", kk: "Пульмонолог / Ревматолог" },
  "Scombroid food poisoning": { ru: "Терапевт / Аллерголог", en: "GP / Allergist", kk: "Терапевт / Аллерголог" },
  "Spontaneous pneumothorax": { ru: "СКОРАЯ ПОМОЩЬ (103) / Хирург", en: "EMERGENCY (911) / Surgeon", kk: "ЖЕДЕЛ ЖӘРДЕМ (103) / Хирург" },
  "Spontaneous rib fracture": { ru: "Травматолог", en: "Traumatologist", kk: "Травматолог" },
  "Stable angina": { ru: "Кардиолог", en: "Cardiologist", kk: "Кардиолог" },
  "Tuberculosis": { ru: "Фтизиатр", en: "Phthisiologist (TB Specialist)", kk: "Фтизиатр" },
  "URTI": { ru: "Терапевт / Педиатр", en: "GP / Pediatrician", kk: "Терапевт / Педиатр" },
  "Unstable angina": { ru: "СКОРАЯ ПОМОЩЬ (103) / Кардиолог", en: "EMERGENCY (911) / Cardiologist", kk: "ЖЕДЕЛ ЖӘРДЕМ (103) / Кардиолог" },
  "Viral pharyngitis": { ru: "Терапевт / ЛОР-врач", en: "GP / ENT", kk: "Терапевт / ЛОР" },
  "Whooping cough": { ru: "Инфекционист / Педиатр", en: "Infectious Disease Specialist / Pediatrician", kk: "Инфекционист / Педиатр" },
};

const DISEASE_RECOMMENDATIONS_I18N: Record<string, Record<Lang, string>> = {
  "Gastroenteritis": { ru: "Регидратация (Регидрон), диета (рис, сухари). При боли - спазмолитик.", en: "Rehydration (ORS), diet (rice, crackers). For pain — antispasmodic.", kk: "Регидратация (Регидрон), диета (күріш, кептірілген нан). Ауырғанда — спазмолитик." },
  "Croup": { ru: "Доступ холодного влажного воздуха. Успокоить ребёнка. При затруднении дыхания — 103.", en: "Cool moist air. Calm the child. If breathing is laboured — call 911.", kk: "Салқын ылғалды ауа. Баланы тыныштандырыңыз. Тыныс алу қиындаса — 103." },
  "Scarlet Fever": { ru: "Изоляция. Обильное питьё. Обязательно врач (нужен антибиотик).", en: "Isolation. Plenty of fluids. Doctor required (antibiotics needed).", kk: "Оқшаулау. Мол сұйықтық. Дәрігер міндетті (антибиотик қажет)." },
  "Eczema": { ru: "Увлажнение кожи (эмоленты). Исключить аллергены. Антигистаминные при зуде.", en: "Skin moisturizing (emollients). Avoid allergens. Antihistamines for itching.", kk: "Теріні ылғалдандыру (эмоленттер). Аллергендерді болдырмау. Қышыған кезде антигистаминдер." },
  "Asthma": { ru: "Ингалятор (Сальбутамол/Беродуал). Посадить пациента. Обеспечить воздух.", en: "Inhaler (Salbutamol/Berodual). Sit the patient up. Ensure fresh air.", kk: "Ингалятор (Сальбутамол/Беродуал). Пациентті отырғызыңыз. Ауа қамтамасыз етіңіз." },
  "Type 1 Diabetes": { ru: "Срочный анализ крови на сахар. Обильное питьё. Врач немедленно.", en: "Urgent blood sugar test. Plenty of fluids. See doctor immediately.", kk: "Шұғыл қан қантын тексеру. Мол сұйықтық. Дәрігерге дереу жүгініңіз." },
  "Bronchiolitis": { ru: "Увлажнение воздуха, промывание носа. Контроль частоты дыхания.", en: "Humidify air, nasal irrigation. Monitor breathing rate.", kk: "Ауаны ылғалдандыру, мұрынды жуу. Тыныс алу жиілігін бақылау." },
  "Meningitis": { ru: "НЕМЕДЛЕННО СКОРУЮ. Опасно для жизни. Не давать обезболивающие до осмотра.", en: "CALL EMERGENCY IMMEDIATELY. Life-threatening. Do not give painkillers before examination.", kk: "ДЕРЕУ ЖЕДЕЛ ЖӘРДЕМ. Өмірге қауіпті. Тексерілгенге дейін ауырсыну басатын дәрі бермеңіз." },
  "Chickenpox": { ru: "Не чесать (Каламин/Зеленка). Жаропонижающее (НЕ Аспирин!).", en: "Don't scratch (Calamine/antiseptic). Antipyretic (NOT Aspirin!).", kk: "Қасымаңыз (Каламин/Зеленка). Қызуды түсіретін дәрі (Аспирин ЕМЕС!)." },
  "Appendicitis": { ru: "Холод на живот. НЕ пить, НЕ есть, НЕ принимать обезболивающие. Вызвать 103.", en: "Ice on abdomen. DO NOT drink, eat, or take painkillers. Call 911.", kk: "Іш үстіне суық. Ішпеңіз, жемеңіз, ауырсыну басатын дәрі қабылдамаңыз. 103 шақырыңыз." },
  "Common Cold": { ru: "Тёплое питьё, промывание носа, отдых. Витамин С.", en: "Warm fluids, nasal rinse, rest. Vitamin C.", kk: "Жылы сұйықтық, мұрынды жуу, демалыс. С витамині." },
  "Acute COPD exacerbation / infection": { ru: "Бронхолитики, кортикостероиды по назначению. Срочная консультация врача.", en: "Bronchodilators, corticosteroids as prescribed. Urgent medical consultation.", kk: "Бронходилататорлар, кортикостероидтар. Шұғыл дәрігер консультациясы." },
  "Acute dystonic reactions": { ru: "Немедленная отмена препарата. Антихолинергические средства. Срочно к врачу.", en: "Immediate drug withdrawal. Anticholinergic agents. Seek medical care urgently.", kk: "Препаратты дереу тоқтату. Антихолинергиялық препараттар. Жедел дәрігерге жүгіну." },
  "Acute laryngitis": { ru: "Голосовой покой, тёплое питьё, увлажнение воздуха.", en: "Voice rest, warm fluids, humidify air.", kk: "Дауысты тыныштандыру, жылы сұйықтық, ауаны ылғалдандыру." },
  "Acute otitis media": { ru: "Жаропонижающее, обезболивающее. Консультация ЛОР.", en: "Antipyretic, analgesic. ENT consultation.", kk: "Қызуды түсіретін дәрі. ЛОР консультациясы." },
  "Acute pulmonary edema": { ru: "СКОРАЯ НЕМЕДЛЕННО. Положение сидя, кислород.", en: "EMERGENCY IMMEDIATELY. Sitting position, oxygen.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Отырған қалып, оттегі." },
  "Acute rhinosinusitis": { ru: "Промывание носа солевым раствором. При затяжном течении — ЛОР.", en: "Nasal saline irrigation. ENT if prolonged.", kk: "Тұзды ерітіндімен мұрынды жуу. Созылса — ЛОР." },
  "Allergic sinusitis": { ru: "Антигистаминные, назальные кортикостероиды, избегать аллергенов.", en: "Antihistamines, nasal corticosteroids, avoid allergens.", kk: "Антигистаминдер, назальды кортикостероидтар, аллергендерден аулақ болу." },
  "Anaphylaxis": { ru: "СКОРАЯ НЕМЕДЛЕННО. Адреналин внутримышечно.", en: "EMERGENCY IMMEDIATELY. Epinephrine intramuscularly.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Адреналин бұлшық etке." },
  "Anemia": { ru: "Препараты железа / витамин B12 по назначению. Консультация гематолога.", en: "Iron / vitamin B12 as prescribed. Hematologist consultation.", kk: "Темір / В12 витамині. Гематолог консультациясы." },
  "Atrial fibrillation": { ru: "Срочная консультация кардиолога. Антиаритмические препараты.", en: "Urgent cardiologist consultation. Antiarrhythmic drugs.", kk: "Кардиолог шұғыл консультациясы. Антиаритмиялық препараттар." },
  "Boerhaave": { ru: "СКОРАЯ НЕМЕДЛЕННО. Жизнеугрожающее состояние. Хирургическое вмешательство.", en: "EMERGENCY IMMEDIATELY. Life-threatening. Surgical intervention.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Өмірге қауіпті. Хирургиялық операция." },
  "Bronchiectasis": { ru: "Дренажный массаж, муколитики. Антибиотики при обострении. Пульмонолог.", en: "Postural drainage, mucolytics. Antibiotics during exacerbation. Pulmonologist.", kk: "Дренаждық массаж, муколитиктер. Асқынған кезде антибиотиктер." },
  "Bronchitis": { ru: "Покой, обильное питьё, муколитики. При затяжном течении — врач.", en: "Rest, plenty of fluids, mucolytics. Doctor if prolonged.", kk: "Тыныштық, мол сұйықтық, муколитиктер." },
  "Bronchospasm / acute asthma exacerbation": { ru: "Ингаляции сальбутамола немедленно. При тяжёлом приступе — СКОРАЯ.", en: "Salbutamol inhalation immediately. Severe attack — EMERGENCY.", kk: "Сальбутамол ингаляциясы дереу. Ауыр шабуыл — ЖЕДЕЛ ЖӘРДЕМ." },
  "Chagas": { ru: "Антипаразитарные препараты. Консультация инфекциониста.", en: "Antiparasitic drugs. Infectious disease consultation.", kk: "Антипаразиттік препараттар. Инфекционист консультациясы." },
  "Chronic rhinosinusitis": { ru: "Назальные кортикостероиды, промывание носа. Консультация ЛОР.", en: "Nasal corticosteroids, nasal rinse. ENT consultation.", kk: "Назальды кортикостероидтар, мұрынды жуу. ЛОР консультациясы." },
  "Cluster headache": { ru: "Кислородная терапия, триптаны. Консультация невролога.", en: "Oxygen therapy, triptans. Neurologist consultation.", kk: "Оттегі терапиясы, триптандар. Невролог консультациясы." },
  "Ebola": { ru: "СКОРАЯ НЕМЕДЛЕННО. Изоляция. Специализированный стационар.", en: "EMERGENCY IMMEDIATELY. Isolation. Specialized hospital.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Оқшаулау. Мамандандырылған аурухана." },
  "Epiglottitis": { ru: "СКОРАЯ НЕМЕДЛЕННО. Жизнеугрожающее. Госпитализация, антибиотики.", en: "EMERGENCY IMMEDIATELY. Life-threatening. Hospitalization, antibiotics.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Өмірге қауіпті. Ауруханаға жатқызу, антибиотиктер." },
  "GERD": { ru: "Диета, ингибиторы протонной помпы. Консультация гастроэнтеролога.", en: "Diet, proton pump inhibitors. Gastroenterologist consultation.", kk: "Диета, протондық сорғы ингибиторлары. Гастроэнтеролог консультациясы." },
  "Guillain-Barré syndrome": { ru: "СРОЧНАЯ госпитализация. Иммунотерапия (ВВИГ или плазмаферез).", en: "URGENT hospitalization. Immunotherapy (IVIG or plasmapheresis).", kk: "ШҰҒЫЛ ауруханаға жатқызу. Иммунотерапия (ВВИГ немесе плазмаферез)." },
  "HIV (initial infection)": { ru: "Срочная консультация инфекциониста. Антиретровирусная терапия.", en: "Urgent infectious disease consultation. Antiretroviral therapy.", kk: "Инфекционист шұғыл консультациясы. Антиретровирустық терапия." },
  "Influenza": { ru: "Покой, обильное питьё, Парацетамол/Ибупрофен при t>38.5. Не принимать антибиотики без врача.", en: "Rest, plenty of fluids, Paracetamol/Ibuprofen if temp >38.5. No antibiotics without a doctor.", kk: "Тыныштық, мол сұйықтық, t>38.5 кезінде Парацетамол/Ибупрофен." },
  "Inguinal hernia": { ru: "Консультация хирурга. При ущемлении — СКОРАЯ НЕМЕДЛЕННО.", en: "Surgeon consultation. If strangulated — EMERGENCY IMMEDIATELY.", kk: "Хирург консультациясы. Қысылса — ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ." },
  "Larygospasm": { ru: "Успокоить, дышать носом. При повторных эпизодах — ЛОР.", en: "Calm down, breathe through nose. Recurrent episodes — ENT.", kk: "Тыныштандыру, мұрынмен тыныс алу. Қайталанса — ЛОР." },
  "Localized edema": { ru: "Выяснить причину. Холод при травме. Консультация врача.", en: "Find the cause. Cold compress for injury. Doctor consultation.", kk: "Себебін анықтау. Жарақат кезінде суық. Дәрігер консультациясы." },
  "Myasthenia gravis": { ru: "Ингибиторы холинэстеразы по назначению. При кризе — СКОРАЯ.", en: "Cholinesterase inhibitors as prescribed. Crisis — EMERGENCY.", kk: "Холинэстераза ингибиторлары. Криз кезінде — ЖЕДЕЛ ЖӘРДЕМ." },
  "Myocarditis": { ru: "Срочная госпитализация. Постельный режим, кардиолог.", en: "Urgent hospitalization. Bed rest, cardiologist.", kk: "Шұғыл ауруханаға жатқызу. Төсек режимі, кардиолог." },
  "PSVT": { ru: "Вагусные пробы (Вальсальва). При неэффективности — кардиолог/СКОРАЯ.", en: "Vagal maneuvers (Valsalva). If ineffective — cardiologist/EMERGENCY.", kk: "Вагусты сынамалар. Тиімсіз болса — кардиолог/ЖЕДЕЛ ЖӘРДЕМ." },
  "Pancreatic neoplasm": { ru: "Срочная консультация онколога. Дообследование (КТ, биопсия).", en: "Urgent oncologist consultation. Further workup (CT, biopsy).", kk: "Онколог шұғыл консультациясы. Толық тексеру (КТ, биопсия)." },
  "Panic attack": { ru: "Дыхательные упражнения. Успокоительные. Консультация психолога.", en: "Breathing exercises. Anxiolytics. Psychologist consultation.", kk: "Тыныс алу жаттығулары. Тыныштандырғыш дәрілер. Психолог консультациясы." },
  "Pericarditis": { ru: "НПВП, покой. Консультация кардиолога обязательна.", en: "NSAIDs, rest. Cardiologist consultation required.", kk: "НПВП, тыныштық. Кардиолог консультациясы міндетті." },
  "Pneumonia": { ru: "Рентген лёгких. Врач назначит антибиотик. Дыхательная гимнастика.", en: "Chest X-ray. Doctor will prescribe antibiotics. Breathing exercises.", kk: "Өкпе рентгені. Дәрігер антибиотик тағайындайды. Тыныс алу гимнастикасы." },
  "Possible NSTEMI / STEMI": { ru: "СКОРАЯ НЕМЕДЛЕННО. Аспирин 325 мг. Нитроглицерин сублингвально.", en: "EMERGENCY IMMEDIATELY. Aspirin 325 mg. Nitroglycerin sublingually.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Аспирин 325 мг. Нитроглицерин тіл астына." },
  "Pulmonary embolism": { ru: "СКОРАЯ НЕМЕДЛЕННО. Антикоагулянты. Жизнеугрожающее состояние.", en: "EMERGENCY IMMEDIATELY. Anticoagulants. Life-threatening condition.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Антикоагулянттар. Өмірге қауіпті жағдай." },
  "Pulmonary neoplasm": { ru: "Срочная консультация пульмонолога и онколога. КТ грудной клетки.", en: "Urgent pulmonologist and oncologist consultation. Chest CT.", kk: "Пульмонолог және онколог шұғыл консультациясы. Кеуде КТ." },
  "SLE": { ru: "Гидроксихлорохин, кортикостероиды по назначению. Защита от солнца.", en: "Hydroxychloroquine, corticosteroids as prescribed. Sun protection.", kk: "Гидроксихлорохин, кортикостероидтар. Күннен қорғану." },
  "Sarcoidosis": { ru: "Кортикостероиды при симптомах. Наблюдение пульмонолога.", en: "Corticosteroids if symptomatic. Pulmonologist follow-up.", kk: "Симптомдар кезінде кортикостероидтар. Пульмонолог бақылауы." },
  "Scombroid food poisoning": { ru: "Антигистаминные, обильное питьё. Симптомы проходят за 6-12 часов.", en: "Antihistamines, plenty of fluids. Symptoms resolve in 6-12 hours.", kk: "Антигистаминдер, мол сұйықтық. Симптомдар 6-12 сағатта өтеді." },
  "Spontaneous pneumothorax": { ru: "СКОРАЯ НЕМЕДЛЕННО. Дренирование плевральной полости.", en: "EMERGENCY IMMEDIATELY. Pleural drainage required.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Плевралды қуысты дренаждау." },
  "Spontaneous rib fracture": { ru: "Обезболивание. Консультация травматолога. Исключить патологические причины.", en: "Pain relief. Traumatologist consultation. Rule out pathological causes.", kk: "Ауырсынуды басу. Травматолог консультациясы. Патологиялық себептерді жоққа шығару." },
  "Stable angina": { ru: "Нитраты при приступе. Бета-блокаторы, антиагреганты. Наблюдение кардиолога.", en: "Nitrates during attack. Beta-blockers, antiplatelets. Cardiologist follow-up.", kk: "Ұстама кезінде нитраттар. Бета-блокаторлар. Кардиолог бақылауы." },
  "Tuberculosis": { ru: "Срочная консультация фтизиатра. Длительная противотуберкулёзная терапия.", en: "Urgent TB specialist consultation. Long-term anti-TB therapy.", kk: "Фтизиатр шұғыл консультациясы. Ұзақ мерзімді туберкулезге қарсы терапия." },
  "URTI": { ru: "Покой, тёплое питьё, промывание носа, жаропонижающее при необходимости.", en: "Rest, warm fluids, nasal rinse, antipyretic if needed.", kk: "Тыныштық, жылы сұйықтық, мұрынды жуу, қажет болса қызуды түсіретін дәрі." },
  "Unstable angina": { ru: "СКОРАЯ НЕМЕДЛЕННО. Аспирин, нитроглицерин. Требует срочной госпитализации.", en: "EMERGENCY IMMEDIATELY. Aspirin, nitroglycerin. Urgent hospitalization required.", kk: "ЖЕДЕЛ ЖӘРДЕМ ДЕРЕУ. Аспирин, нитроглицерин. Шұғыл ауруханаға жатқызу." },
  "Viral pharyngitis": { ru: "Полоскание горла, тёплое питьё, жаропонижающее при необходимости.", en: "Gargling, warm fluids, antipyretic if needed.", kk: "Тамақты шайқу, жылы сұйықтық, қажет болса қызуды түсіретін дәрі." },
  "Whooping cough": { ru: "Азитромицин на ранних стадиях. Изоляция пациента. Консультация врача.", en: "Azithromycin in early stages. Isolate patient. Doctor consultation.", kk: "Ерте кезеңде азитромицин. Пациентті оқшаулау. Дәрігер консультациясы." },
};

export function getDiseaseLabel(disease: string, lang: Lang = "ru"): string {
  return DISEASE_LABELS_I18N[disease]?.[lang] || DISEASE_LABELS_I18N[disease]?.ru || disease;
}

export function getDiseaseDoctor(disease: string, lang: Lang = "ru"): string {
  return DISEASE_DOCTORS_I18N[disease]?.[lang] || DISEASE_DOCTORS_I18N[disease]?.ru || "";
}

export function getDiseaseRecommendation(disease: string, lang: Lang = "ru"): string {
  return DISEASE_RECOMMENDATIONS_I18N[disease]?.[lang] || DISEASE_RECOMMENDATIONS_I18N[disease]?.ru || "";
}

// Default Russian exports for backward compatibility
export const DISEASE_LABELS: Record<string, string> = Object.fromEntries(
  Object.entries(DISEASE_LABELS_I18N).map(([k, v]) => [k, v.ru])
);
export const DISEASE_DOCTORS: Record<string, string> = Object.fromEntries(
  Object.entries(DISEASE_DOCTORS_I18N).map(([k, v]) => [k, v.ru])
);
export const DISEASE_RECOMMENDATIONS: Record<string, string> = Object.fromEntries(
  Object.entries(DISEASE_RECOMMENDATIONS_I18N).map(([k, v]) => [k, v.ru])
);
