import jsPDF from "jspdf";
import type { PatientInfo, HistoryEntry } from "./api";
import { DISEASE_LABELS } from "./diseaseWeights";

export function generatePatientPDF(
  patientInfo: PatientInfo,
  history: HistoryEntry[],
  doctorName: string
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFontSize(18);
  doc.text("Medical Report / Meditsinalnyi otchyot", pageWidth / 2, y, { align: "center" });
  y += 12;

  // Patient info
  doc.setFontSize(12);
  doc.text(`Patient: ${patientInfo.full_name}`, 20, y);
  y += 7;
  doc.text(`ID: ${patientInfo.patient_id}`, 20, y);
  y += 7;
  if (patientInfo.city) {
    doc.text(`City: ${patientInfo.city}`, 20, y);
    y += 7;
  }
  doc.text(`Registration: ${patientInfo.created_at?.split(" ")[0] || patientInfo.created_at}`, 20, y);
  y += 7;
  doc.text(`Report date: ${new Date().toLocaleDateString("ru-RU")}`, 20, y);
  y += 7;
  doc.text(`Doctor: ${doctorName}`, 20, y);
  y += 12;

  // Separator
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // History header
  doc.setFontSize(14);
  doc.text("Diagnosis History", 20, y);
  y += 10;

  doc.setFontSize(10);

  if (history.length === 0) {
    doc.text("No records found.", 20, y);
  } else {
    for (const entry of history) {
      // Check if we need a new page
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      const diseaseLabel = DISEASE_LABELS[entry.disease_predict] || entry.disease_predict;
      const date = entry.created_at?.split("T")[0] || entry.created_at?.split(" ")[0] || "";
      const score = entry.score !== null ? `${Math.round(entry.score * 100)}%` : "N/A";

      doc.setFontSize(11);
      doc.text(`${date} - ${diseaseLabel} (${score})`, 20, y);
      y += 6;

      doc.setFontSize(9);
      if (entry.disease_setup && entry.disease_setup !== "Nothing") {
        doc.text(`  Doctor diagnosis: ${entry.disease_setup}`, 25, y);
        y += 5;
      }
      if (entry.recept) {
        const receptLines = doc.splitTextToSize(`  Recommendations: ${entry.recept}`, pageWidth - 50);
        doc.text(receptLines, 25, y);
        y += receptLines.length * 4.5;
      }
      if (entry.doctor_name) {
        doc.text(`  Verified by: ${entry.doctor_name}`, 25, y);
        y += 5;
      }

      y += 5;
    }
  }

  // Footer
  y = Math.max(y + 10, 250);
  if (y > 270) {
    doc.addPage();
    y = 250;
  }
  doc.setFontSize(8);
  doc.text(
    "Generated by TMS (Triage Medical System). This document is for informational purposes only.",
    pageWidth / 2,
    285,
    { align: "center" }
  );

  doc.save(`patient_${patientInfo.patient_id}_report.pdf`);
}
