export const SYMPTOM_LIST = [
  "ABDOMINAL_PAIN",
  "CHEST_PAIN",
  "COUGH",
  "DEHYDRATION",
  "DIARRHEA",
  "FEVER",
  "HEADACHE",
  "ITCHING",
  "MUSCLE_ACHES",
  "NAUSEA",
  "NECK_STIFFNESS",
  "PHOTOPHOBIA",
  "POLYDIPSIA",
  "POLYURIA",
  "RASH",
  "RESPIRATORY_DISTRESS",
  "RUNNY_NOSE",
  "SNEEZING",
  "SORE_THROAT",
  "STRIDOR",
  "VOMITING",
  "WEIGHT_LOSS",
  "WHEEZING",
] as const;

export type SymptomCode = (typeof SYMPTOM_LIST)[number];

export const SYMPTOM_LABELS: Record<SymptomCode, string> = {
  ABDOMINAL_PAIN: "Боль в животе",
  CHEST_PAIN: "Боль в груди",
  COUGH: "Кашель",
  DEHYDRATION: "Обезвоживание",
  DIARRHEA: "Диарея",
  FEVER: "Температура",
  HEADACHE: "Головная боль",
  ITCHING: "Зуд",
  MUSCLE_ACHES: "Боль в мышцах",
  NAUSEA: "Тошнота",
  NECK_STIFFNESS: "Ригидность шеи",
  PHOTOPHOBIA: "Светобоязнь",
  POLYDIPSIA: "Повышенная жажда",
  POLYURIA: "Частое мочеиспускание",
  RASH: "Сыпь",
  RESPIRATORY_DISTRESS: "Затруднённое дыхание",
  RUNNY_NOSE: "Насморк",
  SNEEZING: "Чихание",
  SORE_THROAT: "Боль в горле",
  STRIDOR: "Стридор",
  VOMITING: "Рвота",
  WEIGHT_LOSS: "Потеря веса",
  WHEEZING: "Хрипы",
};
